name: 'Build WNDR3700v1 SFE (Debug Enabled)'

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt Version (e.g., 23.05.3)'
        required: true
        default: '23.05.3'

env:
  OPENWRT_VERSION: ${{ github.event.inputs.openwrt_version || '23.05.3' }}
  CONFIG_FILE: 'wndr3700-v1-sfe-debug.config'
  TZ: 'UTC'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex g++ gawk gcc-multilib gettext \
          git libncurses5-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev \
          file wget

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/openwrt/openwrt.git -b v${{ env.OPENWRT_VERSION }} --depth 1 openwrt

      - name: Update and install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: Run build script
        working-directory: ./openwrt
        run: |
          cp ../build_openwrt.sh .
          chmod +x build_openwrt.sh
          ./build_openwrt.sh

      - name: Load custom configuration
        run: |
          cp ${{ github.workspace }}/configs/${{ env.CONFIG_FILE }} openwrt/.config
          cd openwrt
          make defconfig

      - name: Download packages
        working-directory: ./openwrt
        run: |
          make download -j$(nproc)

      - name: Build firmware
        working-directory: ./openwrt
        run: |
          # Force a rerun
          make -j$(nproc) V=s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-${{ env.OPENWRT_VERSION }}-${{ env.CONFIG_FILE }}
          path: openwrt/bin/targets/ath79/generic/
